### ISSUE TITLE
Shifty does not disable at sunrise.

### ISSUE THREAD

**Issue by villiansv** [thompsonate/Shifty#25] opened 2017-11-24 11:10 UTC
The problem is this only happens once a day so I can't reliably reproduce/test it. Let me describe my usual routine when I notice it.

Night Shift is enabled sunset to sunrise. No scheduled dark mode or anything. It will correctly turn on at sunset.

In the evening, I will watch some series with IINA (video player app). I've disabled night shift for this app, and Shifty correctly toggles on/off whenever IINA is in the foreground. No issues there.

I will eventually close the screen of the laptop (2016 tbMBP by the way) and go to bed. In the morning, I will open the screen _after_ sunrise but night shift will still be on. A quick look in System Preferences - Displays - Night Shift shows that the Manual Turn On Until Sunrise is checked (though at no point did I manually toggle night shift).

Whenever this has happened, I've shut down shifty, disabled and re-enabled night shift, and turned Shifty back on. The same thing keeps happening. I _think_ it began in 0.3 but honestly can't be sure. It's definitely happening now in 0.4.

**Comment by choco** [comment] 2017-11-24 21:45
I was just about to open an issue myself. I've been experiencing the exact same problem:
1. Night Shift is enabled from  Sunset to Sunrise
2. I close my computer lid at night when Night Shift is enabled
3. I reopen it in the morning after sunrise, Night Shift is still enabled and won't automatically deactivate

**Comment by jostyee** [comment] 2017-11-25 04:58
I've met the same issue with v0.4, while v0.3 worked well.

**Comment by lorenzofanchi** [comment] 2017-11-25 07:49
I've been experiencing the issue described by choco since I started using the app (v0.2 if I remember correctly). Definitely happened on v0.3 for me as well. Just updated to v0.4, so can't say for that version just yet..

**Comment by CENGOiSM** [comment] 2017-11-25 11:32
Same with me. Some additional points.
1. On the login screen at wake up night shift is correctly disabled, but will be activated once I log in.
2. Dark mode will toggle correctly. So at sunrise it is disabled, but night shift will stay active.

I've also started with v0.3, v0.3 hase the same problem.

**Comment by thompsonate** [comment] 2017-11-25 21:08
I've experienced this at least as far back as 0.2. I don't really have any idea what is causing this yet. In 0.3, I added a check on screen wake to set Night Shift to its scheduled state. Obviously that doesn't appear to have worked. I will double check this code soon to make sure it's working as intended, but it's tough since this issue is hard to reproduce. It doesn't even happen every morning for me.

I'm wondering if this is possibly a macOS bug. Has anyone experienced this while Shifty is not running?

@villiansv Is IINA still in the foreground when you open your computer? Night Shift should definitely not be enabled in that case.

**Comment by villiansv** [comment] 2017-11-25 21:13
@thompsonate No IINA is not running. I quit it before going to bed. I also don’t experience the issue every day but it does happen more often than not.

**Comment by choco** [comment] 2017-11-27 11:37
By taking a quick look `isShiftForAppEnabled` may not get updated since Shifty may miss the `blueLightNotification` in this situation. I think a good solution would be to update `isShiftForAppEnabled` in the action of the observer for `screensDidWakeNotification`

**Comment by thompsonate** [comment] 2017-12-28 06:33
Fixed in 67b01f4. Thanks for the lead @choco. That's exactly what was happening.

**Closed** 2017-12-28 06:33 UTC
Labels: bug

**Comment by jostyee** [comment] 2018-01-01 14:15
@thompsonate When can we get an update w/ this fix? It's really annoying.

**Comment by thompsonate** [comment] 2018-01-01 16:45
@jostyee I’m planning on putting out an update today.
