### ISSUE TITLE
1.1.1 Not launching on Mojave (Beta)

### ISSUE THREAD

**Issue by thefella** [thompsonate/Shifty#86] opened 2019-06-21 22:04 UTC
I'm not sure when this started or what caused it, but Shifty stopped working. I can't get it to launch at all now. I've tried rebooting, reinstalling it, but no luck. I've attached the crash diagnostics.

It may just be related to the beta, but everything else seems to be running fine.

[Shifty_2019-06-21-224601.crash.zip](https://github.com/thompsonate/Shifty/files/3316164/Shifty_2019-06-21-224601.crash.zip)

**Comment by petervannes** [comment] 2019-06-25 20:57
Having same issue on 10.14.6 Beta (18G48f)
[Shifty_2019-06-25-225212_Chigatze-1505.crash.zip](https://github.com/thompsonate/Shifty/files/3327244/Shifty_2019-06-25-225212_Chigatze-1505.crash.zip)

**Comment by Lemierre** [comment] 2019-07-11 11:38
The same on 10.14.6 (18G71a)

**Comment by arichard** [comment] 2019-07-22 19:14
Same here since installing 10.14.6 (final version released today).

**Comment by haplm** [comment] 2019-07-23 07:25
Same here, final version of 10.14.6

**Comment by choco** [comment] 2019-07-23 10:15
I'm sorry everyone, I've been job hunting and that is taking all my time basically. I'll take a look right now...

**Comment by choco** [comment] 2019-07-23 10:30
Ok I found the issue, I think. Unfortunately I can't push a new release myself so pinging either @thompsonate @LumingYin.

In the mean time here's a build signed with my DeveloperID so you can test if the issue is fixed.
[Shifty.zip](https://github.com/thompsonate/Shifty/files/3421567/Shifty.zip)

**Comment by thefella** [comment] 2019-07-23 10:39
That seems to have fixed it @choco!

**Comment by Lemierre** [comment] 2019-07-23 11:35
> Ok I found the issue, I think. Unfortunately I can't push a new release myself so pinging either @thompsonate @LumingYin.
> 
> In the mean time here's a build signed with my DeveloperID so you can test if the issue is fixed.
> [Shifty.zip](https://github.com/thompsonate/Shifty/files/3421567/Shifty.zip)

It works but it doesn't enable Dark Mode, only Night Shift

**Comment by choco** [comment] 2019-07-23 11:44
> It works but it doesn't enable Dark Mode, only Night Shift

You can open a new issue for that, but it works on my setup. Have you tried setting a keyboard shortcut to toggle Dark mode and see if it works? Also keep in mind that Dark mode get enabled only according to schedule (i.e. it doesn't work if you manually enable night shift)

**Comment by Lemierre** [comment] 2019-07-23 11:52
> > It works but it doesn't enable Dark Mode, only Night Shift
> 
> Also keep in mind that Dark mode get enabled only according to schedule (i.e. it doesn't work if you manually enable night shift)

Thank you for clarification! I've tried to toggle in Dark Mode manually :) It works with a shortcut.

**Comment by andrew-lozoya** [comment] 2019-07-26 17:55
Thanks for the fix! Was having issues on 10.14.6

**Comment by Asgardsurfer** [comment] 2019-07-28 14:03
Thanks choco, now works in 10.14.6!

**Comment by JeffBargmann** [comment] 2019-08-11 05:27
Confirmed resolved by @choco in https://github.com/thompsonate/Shifty/pull/87. Awaiting merge!

**Closed** 2019-08-11 16:22 UTC
Labels: bug

**Comment by thompsonate** [comment] 2019-08-11 16:44
Update released! Thanks for the help everyone and sorry I couldn't get to this sooner.

**Comment by berstend** [comment] 2019-08-12 14:37
@thompsonate great job, can confirm it working now with `1.1.2` on Mojave. I just came across shifty yesterday and it would crash after the initial launch (1.1.1), so I'm quite happy about the timing of the fix 😄

I'm impressed with the per-site toggle supporting Chrome, this app is already better than Flux has been! 👍
